import sys
from playwright.sync_api import sync_playwright
url, out = sys.argv[1], sys.argv[2]
errs=[]
with sync_playwright() as p:
    b = p.chromium.launch()
    pg = b.new_page(viewport={"width":800,"height":480}, has_touch=True)
    pg.on("pageerror", lambda e: errs.append(str(e)))
    pg.on("console", lambda m: m.type=="error" and errs.append(m.text))
    pg.goto(url); pg.wait_for_timeout(2000)
    pg.click(".nav-item[data-id=satellites]"); pg.wait_for_timeout(300)
    pg.click(".search .field"); pg.wait_for_timeout(300)
    for k in ["n","o","a"]: pg.click(f".osk-key:text-is('{k}')")
    pg.wait_for_timeout(300); pg.screenshot(path=f"{out}/osk.png")
    pg.click(".osk-key.k-enter"); pg.wait_for_timeout(300)
    pg.click(".type-btn"); pg.wait_for_timeout(400); pg.screenshot(path=f"{out}/type.png")
    pg.click(".chk-item:has-text('Weather')"); pg.click(".dialog-actions .btn.primary"); pg.wait_for_timeout(300)
    pg.screenshot(path=f"{out}/filtered.png")
    pg.click(".sat-row >> nth=0 >> .sat-info"); pg.wait_for_timeout(400); pg.screenshot(path=f"{out}/details.png")
    pg.click(".dialog-actions .btn.primary")
    pg.click(".nav-item[data-id=passes]"); pg.wait_for_timeout(300)
    pg.click(".pass >> nth=3"); pg.wait_for_timeout(800); pg.screenshot(path=f"{out}/radar-noaa.png")
    pg.click(".nav-item[data-id=settings]"); pg.wait_for_timeout(300)
    pg.click(".srow:has-text('Night mode') .switch"); pg.wait_for_timeout(300)
    pg.click(".nav-item[data-id=map]"); pg.wait_for_timeout(800); pg.screenshot(path=f"{out}/night-map.png")
    pg.click(".nav-item[data-id=settings]"); pg.click(".srow:has-text('Night mode') .switch")
    pg.click(".srow:has-text('Rotate screen') button:text-is('90°')"); pg.wait_for_timeout(600)
    pg.screenshot(path=f"{out}/rot90.png")
    pg.click(".nav-item[data-id=passes]"); pg.wait_for_timeout(500); pg.screenshot(path=f"{out}/rot90-passes.png")
    pg.click(".nav-item[data-id=settings]"); pg.wait_for_timeout(300)
    pg.click(".srow:has-text('Rotate screen') button:text-is('0°')"); pg.wait_for_timeout(600)
    pg.screenshot(path=f"{out}/rot0.png")
    b.close()
print(errs or "no errors")
